# Generated by Django 2.2.4 on 2020-07-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200, verbose_name='Название запчасти')),
                ('supplier', models.CharField(max_length=50, verbose_name='Поставщик')),
                ('clinic', models.CharField(max_length=50, verbose_name='ЛПУ')),
                ('device', models.CharField(blank=True, max_length=100, verbose_name='Аппарат')),
                ('engineer', models.CharField(max_length=50, verbose_name='Техник')),
                ('supply', models.CharField(choices=[('Нет', 'Нет'), ('Да', 'Да')], default='Нет', max_length=5, verbose_name='Состояние поставки заказа')),
                ('supply_date', models.DateField(blank=True, null=True, verbose_name='Дата прихода заказа')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('bill_number', models.CharField(blank=True, max_length=50, verbose_name='Номер счёта')),
                ('bill_date', models.DateField(blank=True, null=True, verbose_name='Дата счёта')),
                ('bill_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Сумма в счёте')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заказ по счёту',
                'verbose_name_plural': 'Заказы по счёту',
            },
        ),
    ]
