# Generated by Django 3.1 on 2020-08-27 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='order_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='supply',
            field=models.CharField(choices=[('Да', 'Получили'), ('Нет', 'Ожидаем')], default='Нет', max_length=5, verbose_name='Состояние поставки заказа'),
        ),
    ]
