# Generated by Django 2.2.4 on 2020-07-05 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20200706_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='supply',
            field=models.CharField(choices=[('Нет', 'Нет'), ('Да', 'Да')], default='Нет', max_length=5, verbose_name='Состояние поставки заказа'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='supply_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 7, 6), null=True, verbose_name='Дата прихода заказа'),
        ),
    ]
