# Generated by Django 3.1 on 2020-08-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_order_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='supply_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прихода заказа'),
        ),
    ]
