# Generated by Django 2.2.4 on 2020-07-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20200706_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='supply',
            field=models.BooleanField(choices=[(True, 'Получили'), (False, 'Ожидаем')], default=False, verbose_name='Состояние поставки заказа'),
        ),
    ]
