# Generated by Django 2.2.4 on 2020-07-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_auto_20200706_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='supply',
            field=models.CharField(choices=[('Нет', 'Ожидаем'), ('Да', 'Получили')], default='Нет', max_length=5, verbose_name='Состояние поставки заказа'),
        ),
    ]
