# Generated by Django 3.1 on 2020-08-19 12:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bills', '0007_auto_20200725_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['pk'], 'verbose_name': 'Заказ по счёту', 'verbose_name_plural': 'Заказы по счёту'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='supply',
            field=models.CharField(choices=[('Да', 'Получили'), ('Нет', 'Ожидаем')], default='Нет', max_length=5, verbose_name='Состояние поставки заказа'),
        ),
    ]
