# Generated by Django 3.1 on 2020-08-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_auto_20200820_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
