# Generated by Django 3.1 on 2020-08-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_auto_20200819_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
