# Generated by Django 3.1 on 2020-08-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='supply',
            field=models.CharField(choices=[('Нет', 'Ожидаем'), ('Да', 'Получили')], default='Нет', max_length=5, verbose_name='Состояние поставки заказа'),
        ),
    ]
