"""
Django settings for medtehsite project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import sys
import django_heroku

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_ROOT = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(PROJECT_ROOT, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'yn3yuv!8ktv714_2^0v#m95j-6lja-v1+ys!hsdh5#_t9+k+3p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ['*']
# ALLOWED_HOSTS = ['http://mt-vlg.herokuapp.com/']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

#    'medtehsite.apps.core',
    # 'cash',
    # 'bill',
    'bills',

    'crispy_forms',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medtehsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'medtehsite/templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medtehsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'ru-Ru'     # for django 3.1
# LANGUAGE_CODE = 'en-us'     # default
# LANGUAGE_CODE = 'Ru'        # for django ~2.2

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Europe/Volgograd'

USE_I18N = True

# USE_L10N = False
USE_L10N = True     # включил для использования разделителя разрядов

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

# EMAIL_HOST_USER = mikhail.iv85@mail.ru
EMAIL_HOST_USER = 'mikhail.iv85'
EMAIL_HOST_PASSWORD = 'Djkjulf1*'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = 465

DATE_INPUT_FORMATS = [
    '%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y',  # '2006-10-25', '10/25/2006', '10/25/06'
    '%b %d %Y', '%b %d, %y',             # 'Oct 25 2006', 'Oct 25, 06'
    '%d %b %Y', '%d %b, %y',             # '25 Oct 2006', '25 Oct, 06'
    '%B %d %Y', '%B %d, %y',             # 'October 25 2006', 'October 25, 06'
    '%d %B %Y', '%d %B, %y',             # '25 October 2006', '25 October, 06'
    '%d.%m.%Y', '%d.%m.%y',              # '25.06.2020', '25.06.20'
    '%d %m %Y', '%d %m %y',              # '25 06 2020', '25 06 20'
]

DATE_FORMAT = 'j E Y'

LOGIN_REDIRECT_URL = 'bills:bill_list'
LOGOUT_REDIRECT_URL = 'bills:bill_list'

THOUSAND_SEPARATOR = ' '
USE_THOUSAND_SEPARATOR = True
NUMBER_GROUPING = 3


django_heroku.settings(locals())

